export GITHUB_USERNAME=""
export GITHUB_TOKEN=""
export GH_TOKEN=""
export SONAR_TOKEN=""
export NEXT_TELEMETRY_DISABLED=1
export RAIDRUNNER_BLIZZARD_CLIENT_ID=""
export RAIDRUNNER_BLIZZARD_SECRET_ID=""
